### ISSUE TITLE
homepage redesign implementation

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#1177]
This is a list of the outstanding implementation details for the Trilogy design. Some of these tasks are large and will be split off into separate tasks:

Open questions:

- [x] Create a version of their navigation which is discoverable by users and build it @koryfey @artuoma 
- [x] encapsulate navigation code in web component without any 3rd party library dependencies
- [x] Design shortfalls in doc from Trilogy
spriteable too, maybe easier to manage as a subset than the icon font)
- [x] remove jquery dependency from provided youtube launch code 
- [x] Move the generated file tracker (htmlmap) to the docs folder so it is deleted when you blow away the files it reviews (done in the trilogydev branch)
- [x] Review how the amount of css overlap between the rest of the site and the new homepage css, can we combine it or should it stay split?
- [x] debounce please: https://github.com/cagov/covid19/issues/1322
- [x] build system: https://github.com/cagov/covid19/issues/1299
- [x] I think KK fixed this https://github.com/cagov/covid19/issues/1298
- [x] is useful widget styling: https://github.com/cagov/covid19/issues/1297
- [x] h1 into WP: https://github.com/cagov/covid19/issues/1293
- [x] announcements: https://github.com/cagov/covid19/issues/1295
- [x] fix footer: https://github.com/cagov/covid19/issues/1296
- [x] widths: https://github.com/cagov/covid19/issues/1321
- [x] twitter: https://github.com/cagov/covid19/issues/1275
- [x] new site nav: https://github.com/cagov/covid19/issues/1216
- [x] Review rest of site for bugs caused by header and footer updates
- [x] videos into WP + translatable (need to hide videos if we don't get translated ones @carterm ): https://github.com/cagov/covid19/issues/1294

**Comment by aaronhans** [comment]
https://github.com/cagov/covid19/issues/1216

**Comment by aaronhans** [comment]
https://github.com/cagov/covid19/issues/1275

**Comment by aaronhans** [comment]
We have most of the big page pieces created and implemented with full templating so we can begin bug finding and fixing, some known issues:

- [ ] video overlay not closing on first click
- [ ] fixed header not compatible with rest of site headers (move them down or unfix header elsewhere)
- [ ] translated versions of homepage lose header background
- [ ] homepage header background on IE issues
- [ ] translated strings formatting problems in stats module
- [ ] new homepage design issues in Arabic RTL format

**Comment by carterm** [comment]
https://github.com/cagov/covid19/pull/1379

**Comment by abquirarte** [comment]
### social share image
- [ ] Create updated social share image and replace in all pages. 
Now we have: 
![image](https://user-images.githubusercontent.com/9556188/91231941-07bccd80-e6e3-11ea-9c8c-f236e82fe676.png)
![image](https://user-images.githubusercontent.com/9556188/91232002-21f6ab80-e6e3-11ea-8abf-a5a22799025b.png)

At minimum we'd like something that has new colors, fonts.  @adam-little @thepegisin 

### banner
- [ ]  Draft banner language (for Friday roll-out)

**Comment by kenbasart** [comment]
- [ ] Remove old social media box from homepage:

**Comment by kenbasart** [comment]
- [ ] Update anchor link:

https://covid19.ca.gov/roadmap-counties/#track-data

so that it points to the new map. (Note: we are waiting on this link.)

**Comment by traintestbritt** [comment]
I checked off:  instrument new homepage section interactions with GA events (identify what we need to track with @abquirarte and @traintestbritt) (@aaronhans)

Here's a link to the tracking recs I shared (as a google sheet): https://docs.google.com/spreadsheets/d/1ei3bWsSDBQ-GsKWLuFZnpXBdnXsmphev1mBsBUPT98E/edit?usp=sharing

**Comment by abquirarte** [comment]
FYI ONLY- Also tracking TASKS TO GO LIVE on spreadsheet #Dimmer-switch channel (team).

**Comment by aaronhans** [comment]
All issues are completed except items which were already spun off into their own tickets
