### ISSUE TITLE
Content style guide consolidation

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#1202]
## background
We currently have content style guide documented in several places. We need help consolidating the key elements of what we have currently documented into a single place and determine what gaps we have so we can add/enhance our process. 

## Current resources:
- Alpha content guide- handbook version: https://handbook.alpha.ca.gov/en/latest/content/
- [Alpha working doc- content guide](https://docs.google.com/document/d/1YsOO9GL5MXlkVTZ4JQHFefdRwPRgTe_ACNNRsGjs1LI/edit)
- [COVID-19 style notes (March/April 2020)](https://docs.google.com/document/d/1txYjL0T2Qmi6Bn7UMtRyECNGbJpOzVQ5ALtqrVTOPOI/edit)
- [Wiki- inclusivity considerations](https://github.com/cagov/covid19/wiki/Inclusivity-considerations-checklist)

## Tasks
- [x] Review docs 
- [x] Review peer organization resources 
- [x] Update in 1 Google Doc to highlight agreement across documents, identify gaps and inconsistencies, and propose improvements
- [x] Resolve gaps, inconsistencies, and suggestions
- [x] Determine final home for style guide using transparency principles

**Comment by m-sullivan7** [comment]
Content team discussed style guide on September 30 and have agreed to current draft as a v1 version for publication. We will continue iterating as we discuss new standards.

I will discuss with @abquirarte where the style guide will live and some lingering questions for her level upon her return next week.

**Comment by m-sullivan7** [comment]
Have begun loading content into [github wiki](https://github.com/cagov/covid19/wiki/Content-style-guide).

**Comment by m-sullivan7** [comment]
Style guide upload to [github wiki](https://github.com/cagov/covid19/wiki/Content-style-guide) complete. The style guide is launched and will be updated as needed.
