### ISSUE TITLE
Recovery Input page - remove link to survey

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#1391]
### context 
Governor's office would like to remove the link to the recovery survey but keep the page. 🌆 

page: https://covid19.ca.gov/recovery-input/
remove link to this: https://input.covid19.ca.gov/#top

![image](https://user-images.githubusercontent.com/9556188/90943952-06cd2880-e3d1-11ea-868c-f835f714b42c.png)

### timeline
By Friday 8/28/2020

### tasks 

- [x] remove button
- [x] update content (since we will not have a button) 
- [x] Remove page from navigation
- [x] remove references to this page in other parts of the site. 

-Do not kill the page-

**Comment by abquirarte** [comment]
This will have to get cleaned up as part of the new dimmer switch/framework roll-out. 
cc: @thepegisin / @m-sullivan7 perhaps someone else from the content team can help track this one since the two of you are focusing on the broader framework and helping the team track what will have to change in the other pages

ccc: @kenbasart @hannahslee

**Comment by m-sullivan7** [comment]
@abquirarte With dimmer switch draft content and homepage work completed (from my end) for this morning and my blog post meeting with JP not until later this morning, let me see if I can draft an update now. I'll update if I don't have something by lunch.

**Comment by m-sullivan7** [comment]
@abquirarte 
- [Draft revisions](https://docs.google.com/document/d/1bR0XfU-DFk1oLM9XGhXaEFybw85Q8fDlXyg9FkG_xhs/edit?usp=sharing), including button removal
- Only one other page includes a reference to the survey, [Industry Guidance](https://covid19.ca.gov/industry-guidance/)
- Do these changes need to be scheduled for a specific time or can they be made now?

**Comment by abquirarte** [comment]
@m-sullivan7 
Reviewed revisions, look great! 
These changes can be made now ✔️

**Comment by LizNobriga** [comment]
- [x] remove content/link referring to recovery survey on Industry guidance page

**Comment by m-sullivan7** [comment]
https://covid19.ca.gov/recovery-input/ has been updated with new content (confirmed live on site). Navigation no longer contains a link to the page. This issue is complete!

**Comment by abquirarte** [comment]
Awesome work @m-sullivan7 !!!!!
