### ISSUE TITLE
04/02/2020 Updates to covid19.ca.gov 

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#162]
# Updates by noon
- [x] Create Business and employers page
- [x] push contributions link live at 11am 
- [x] Update content on public places- DMV virtual office, new services
- [x] Update "stay home order" banner language: https://github.com/cagov/covid19/issues/151
- [x] In "don't" section update ~go to doctor if you aren't sick~ to: go to doctor unless you call first
- [x] Add housing + homelessness category, page is published: https://github.com/cagov/covid19/issues/49
- [x] Change the order of **latest news** and **find services and information** (Move Latest news to the bottom, move find services up)
![image](https://user-images.githubusercontent.com/9556188/78215065-85015080-746b-11ea-8382-2d1c787b720e.png)
- [x] Push mobile menu updates @artuoma 
- [x] add local county alerts to get "local information" page: https://github.com/cagov/covid19/issues/26  

______________________________________________________________________________________________

## Up next- clean up pages
![image](https://user-images.githubusercontent.com/9556188/78215881-7d42ab80-746d-11ea-9689-6c47baaa8b7e.png)

- [ ] review any applicable recommendations https://github.com/cagov/covid19/issues/133

**Comment by abquirarte** [comment]
- [ ] New page on Taxes: https://covid19.ca.gov/taxes/ 
https://as-go-covid19-d-001.azurewebsites.net/2020/04/02/taxes/

**Comment by abquirarte** [comment]
👏
