### ISSUE TITLE
New page: Food resources 

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#264]
### Context
We connected with CalVolunteers. They compiled a list of resources for people that are facing food scarcity. Here is the [draft that has been approved](https://docs.google.com/document/d/1eTqexEpRCG1ME3YRPwasICo9oWo-3cMJ/edit#) by JIC. 
Saved in our content folder. 

### hemminway score
~Grade 11 of current draft~
As of 4/18- grade 8 

### timeline
By Thursday 

### content captain
@LizNobriga 

### Tasks
- [x] [Review content](https://docs.google.com/document/d/1eTqexEpRCG1ME3YRPwasICo9oWo-3cMJ/edit#) with @thepegisin clean up in Google staging doc
- [x] Create draft page in WP 
- [x] Add to list of translation needs for new content 
- [x] Publish!
- [x] Add to main page

**Comment by abquirarte** [comment]
We got an update, this is on hold for now. 
Content staged in WP with password. Thank you @thepegisin and @LizNobriga 🙏

**Comment by LizNobriga** [comment]
Content updated in WP (with password).

**Comment by abquirarte** [comment]
Made update this AM, the doc should match what we have in WP (with password).

**Comment by LizNobriga** [comment]
New updates to content received from CDA 4/20. Drafting revisions in gdoc.

**Comment by LizNobriga** [comment]
[Revised draft](https://docs.google.com/document/d/1OPOFCyLaxnlJ336689Y_ye-NlygC8M91/edit#) reviewed by @thepegisin and ready for @abquirarte.

**Comment by LizNobriga** [comment]
Updated content live in WP.

**Comment by abquirarte** [comment]
> Updated content live in WP.

Thank you @LizNobriga ! I hear that Friday is the target date. :)

**Comment by LizNobriga** [comment]
Pandemic EBT content added.

**Comment by LizNobriga** [comment]
Moved all Pandemic EBT program info from "CalFresh food benefits" section to "Families with school-aged children" section

**Comment by abquirarte** [comment]
This is now live
