### ISSUE TITLE
New page: California Recovery survey 

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#365]
### Ask
Need to add new page to our website!

**Final content here** 👉 https://docs.google.com/document/d/1B2GpW-fIW5R9pWLC1cWe7clVjyJihsAVJObNYOSukxI/edit#heading=h.eplujx1ks9mn

### Deadline:
needs to be live by 12pm Monday. 

### tasks

- [x] Publish in WP (with pw until ready)
- [x] Add language to banner
> **Provide Input: California Recovery Roadmap**
> California is building a roadmap for modifying the statewide Stay-at-Home order while maintaining community health and resiliency. We need Californians to give input on the best way to reopen different sectors of our economy
>You can provide your input by filling out the survey. 
- [x] Add new page to how you can help column

#### Spanish
- [x]  Translate 
- [x]  Publish in wordpress
- [ ] Add to the column

**Comment by thepegisin** [comment]
- [x]  Publish in WP (with pw until ready) - DONE
