### ISSUE TITLE
New Page: Recovery roadmap 

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#410]
### Timeline
~By this weekend, to be announced Monday.~
ETA: Friday (as of 5/4/2020) 

### Context
We need to create a new page that will house the 4 stages to ending the stay-at-home order. 

The page will summarize the 4 stages and host guidelines (via documents) being released. We will summarize the guidelines and only the summaries will need to be translated. The guidelines will remain as attachments. 

I'm assuming each stage will be it's own page. 

### design
This will require some visual elements (mimicking the slides). This will be high level enough, I see this living on the top of the page so it would be:

- Stay home order
-  Essential jobs
-  **Recovery Roadmap**

### resources:

[**Staging document**] 👉 (https://docs.google.com/document/d/1z21Pjmsc-Usgp0tYCTu9R0zQFwX0jl4V-YIG12g4DjQ/edit)

[Powerpoint of Roadmap](https://drive.google.com/file/d/10QmGGS9Q4a_4zdrASk45nnV1q2ouFZdL/view)

[1st round of guidelines](https://drive.google.com/file/d/1UUaBfW2QxDwy2uwYV-kpBVHAqMljLyGI/view)

**Comment by thepegisin** [comment]
- [x] Initial draft created

**Comment by abquirarte** [comment]
Updated content to reflect how we will structure the guidances (by type vs. by sector). Pasted the ones we know of in our staging doc. @thepegisin

**Comment by abquirarte** [comment]
- [ ] Can the menu sections link to branded pdfs? 
- [ ] Can we add a custom thumbnail for this section of the website to preview on social? 
- [ ] Can there be anchor links to each section of the guidance (i.e. healthcare, manufacturing, etc.)?

#### Tentative guidance types (instead of by sector...) 

• Public Transit and Intercity Passenger Rail   
• Construction
• Retail
• Logistics and Warehousing Facilities
• Manufacturing
• Office workspaces
• Mining and Logging
• Life sciences
• Hotels and Lodging
• Communications Infrastructure
• Real Estate Transaction
• Delivery Services
• Energy and utilities
• Airports
• Ports
• Food Packing 
• Agriculture and Livestock

**Comment by abquirarte** [comment]
@thepegisin 
[roadmap language covid19 5.5 PM.docx](https://github.com/cagov/covid19/files/4584794/roadmap.language.covid19.5.5.PM.docx)

**Comment by abquirarte** [comment]
New content came in. Saved link in current staging doc.

**Comment by abquirarte** [comment]
Closing this issue. 
Updates now tracked in #436
