### ISSUE TITLE
PDF Coordination Plan: Resilience Roadmap

### ISSUE THREAD

**Issue by TamaraIDEJA** [cagov/covid19#436]
### For new page
Reference
- [x] Make sure updates in WP match design and content in staging @artuoma 
- [x] Name PDF exactly as [highlighted in pink for both guidance and checklist](https://docs.google.com/document/d/14IUZDZ9NJrUXKZOJb-20qPwr9OGZLNUYitHpe7oQxWc/edit#heading=h.fmow5n5h5z0w)
- [x] Save PDFs in [this folder.](https://drive.google.com/open?id=1tdEgmxB5L3Bb-RLX8bXjw2ihNBS5k3-5) @KaylaPrusia @LizNobriga @ashleydraper @JasonKarim 
- [x] Publish Guidance and Checklist PDFs on github pdf folder 
- [x] Add metatag descriptions to this page. Include “phase” (trending in our searches now) @thepegisin 
- [x] Social share- thumbnail- needs to be coordinated with @aaronhans 

------------
### Roadmap county variance subpage
- [x] Review content first thing in the AM: [Staging doc here](https://docs.google.com/document/d/1bz5oU2idZ3heF4GLQY7d1jhFVSiylFUbdnDKcAoeFQ0/edit)
- [Published in WP as private](https://as-go-covid19-d-001.azurewebsites.net/2020/05/07/roadmap-counties/)
- [x] Publish
--------------------------
### Other changes 

- [x] Update Stay at home order FAQ- initial updates @thepegisin 
- [x] Update numbers Eng @KaylaPrusia 
- [x] Update numbers Spanish @orielgomez 
- [x] Update Banner Eng @KaylaPrusia 
> **Resilience Roadmap**
Governor Newsom announced the release of industry guidance to help businesses reduce risk and establish a safe, clean environment for workers and customers. Read the guidance, find industry-specific checklists and learn more about [California's resilience roadmap](covid19.ca.gov/roadmap).
- [ ] Update Banner Spanish ☝️ 
- [x] Add as third action link button to main page
![image](https://user-images.githubusercontent.com/9556188/81321566-9aa7fe00-9047-11ea-983c-dc57ebb6cd22.png)

**Coming after 12pm**
~Upload county guidance pdf: covid19.ca.gov/pdf/guidance-counties.pdf~

**Comment by thepegisin** [comment]
Here's the Roadmap page metadescription. @artuoma please insert into Excerpt in WP post.

**State of California's roadmap to reopening businesses safely. The current phase is Stage 2. Guidance for adapting workplaces to prevent COVID-19 / coronavirus infection.**

**Comment by abquirarte** [comment]
☑️ yay!
