### ISSUE TITLE
New page: Guidance for immigrant communities

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#44]
### context 
Governor will be announcing resources for immigrant communities. They would like to create a page, similar to what we did for the Stress playbooks. 
👉  [Final is here](https://docs.google.com/document/d/1pGE1NAxUNekhDp5hq2H336-dUfIZ-esU/edit) -~updated link 12:26~ updated 2:18 saved in content folder. Archived other doc. 

### timeline 
Draft by Tuesday, to go live by Wednesday

### dependencies 
- We have draft content, but may not be final. Will need to work with SME on this. 
~Outstanding question of whether it makes sense to merge content from "[Fighting discrimination](https://docs.google.com/document/d/1tWJaESWFOIpGOxXrzszda03YWXcNawdGn2w2MFsK5YI/edit)" page that @thepegisin started.~ 

### content captain
@thepegisin working with @orielgomez

### tasks 
- [x] Make sure essential workers Spanish page is formatted as it was intended (all black, only Spanish)
- [x] Send over for translation (this should be posted in both English and Spanish) pages. GO sent translation request. 
- [x] Stage content draft (route for approvals)
- [x] move content in WP Eng and Spanish
- [x] upload pdfs 
- [x] publish

**Comment by coreycaitlin** [comment]
I'd recommend a new question and answer — something like this:

> Will getting screened, tested, or treated for COVID-19 affect my immigration status or eligibility?
> 
> People should follow the guidance of public health professionals and seek testing and treatment when necessary, regardless of immigration status. Immigration officials have confirmed that they will not consider testing, treatment, or preventative care related to COVID-19 as part of a “public charge” rule.

I'm hoping that "public charge" is familiar to the folks who might be worried about this, and I'm not sure we can summarize the rule in plain language concisely and in a way that would allay their fears.

Thoughts @hilaryhb @abquirarte?

**Comment by abquirarte** [comment]
Is there anywhere we can point to that summarizes what public charge is?
Perhaps this: https://www.uscis.gov/greencard/public-charge

Other than that- I think this captures it well @coreycaitlin  👍

**Comment by coreycaitlin** [comment]
Ah good find on that link @abquirarte! I like that it also includes language direct from USCIS reiterating what we're saying.

So the proposed content would be:

> **Will getting screened, tested, or treated for COVID-19 affect my immigration status or eligibility?**
> 
> Follow guidance from public health professionals and seek testing and treatment if you need it, regardless of your immigration status. Immigration officials have confirmed that they will not consider testing, treatment, or preventative care related to COVID-19 as part of a “[public charge](https://www.uscis.gov/greencard/public-charge)” rule. See [guidance for immigrant communities](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/Immigrant-Communities-Guidance.aspx) from the California Department of Public Health (available in multiple languages).

@abquirarte Does that look 👍 to publish?

**Comment by abquirarte** [comment]
Prior comment [Archiving] How to best integrate this resource in the health page?
https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/Guidance-Immigrant.aspx

Suggested language:

_I have a concern or complaint about getting care for COVID-19 under my health insurance. What can I do?
Contact the California Department of Insurance’s Consumer Hotline: (800) 927-4357 [HELP] or go to their website.

Can I get screened or Immigrant Communities:
Public health is focused on ensuring all individuals, regardless of their immigration status, are protected from the outbreak and receive appropriate testing and treatment.
For families that are concerned about the "public charge" rule, immigration officials have confirmed that they will neither consider testing, treatment, nor preventative care related to COVID-19 as part of a “public charge” rule.
Individuals should follow the guidance of our public health professionals and seek testing and treatment when necessary._

Linked doc with comments: https://docs.google.com/document/d/1LEPBrfZxRFS8BUdAZrbk-ZhhfevGoM0NVsqIhH-kKv8/edit#

**Comment by abquirarte** [comment]
[SPANISH COVID-19 IMMIGRANT GUIDANCE CM, OG, LMM.docx](https://github.com/cagov/covid19/files/4479091/SPANISH.COVID-19.IMMIGRANT.GUIDANCE.CM.OG.LMM.docx)

**Comment by abquirarte** [comment]
Now live! 
https://covid19.ca.gov/guide-immigrant-californians/
https://covid19.ca.gov/guia-californianos-inmigrantes/
