### ISSUE TITLE
Update Data 3.0 one-pagers

### ISSUE THREAD

**Issue by mediajunkie** [cagov/covid19#4970]
There are three of them, grouped under this summary page: [Data 3.0 (one pager)](https://docs.google.com/document/d/1V1VE-KunKvvWDQKoLR2RpqNOjBZx4jqbxEzc5CSgudk/edit):

- [ ] [Cases by vax status](https://docs.google.com/document/d/1OGVRkTSgRy-BGWhC4HZHsc5iRKzL2oCY9UD1y5VbwGU/edit)
- [ ] [Variants page](https://docs.google.com/document/d/1YmgWRkw8fgThkYpT8Dp3UIw5OJSNf37sBmfQmXIgQ28/edit)
- [ ] [Trackerbox 3.0](https://docs.google.com/document/d/12p4ceHBXeG2TJOEhf4KJebO5Ndw7BqCFsDnr-9zNKY8/edit)
