### ISSUE TITLE
Remaining example charts for CDPH science branch review

### ISSUE THREAD

**Issue by mediajunkie** [cagov/covid19#4976]
Referring to [this deck](https://docs.google.com/presentation/d/1UMZc7zWMejU3SxcJwo9MbPk4YubSRNA2mNgl8bOue-8/edit): 

- [ ] Slides 5, 7, 8, 15 and 24 but with vaxed on the bottom
- [ ] Slide 8, but for hospitalizations & deaths
- [ ] Slides 9, 16, and 21 but with zero at the center, vaxed pointing left, unvaxed pointing right
