### ISSUE TITLE
ODP/Data Dictionary updates to Data & Tools page for Health Equity charts

### ISSUE THREAD

**Issue by mediajunkie** [cagov/covid19#4977]
This is a pending jira task, [CCG-2008](https://digital-ca-gov.atlassian.net/browse/CCG-2008) - more specifically subtask [CCG-2079](https://digital-ca-gov.atlassian.net/browse/CCG-2079), that may still have steps left to do:

- [x] review section with CIO office and data stewards
- [x] Get tables added to ODP (ask Sam Hayashi and Scott Christman)
- [x] Keep Will Wheeler informed
- [x] Verify updates to [Data & tools (google doc)](https://docs.google.com/document/d/18CrGb-ke03BB1Ai8Fdz2TEaxozcwo65X6InPx2dMKJE/edit)
- [x] Assign to Michael if any remaining edits are still needed

references
- [gmail thread (xian's)](https://mail.google.com/mail/u/0/#inbox/QgrcJHrjCsmQmfJjFZHRwKXdtHtdzFSXxc)
- [Swirlbase record](https://airtable.com/tblmIs67DpOt3B72M/viwYW5mLY5llb1MT8/recKawCj1kbAlR12y?blocks=hide)
