### ISSUE TITLE
Cases by vax status

### ISSUE THREAD

**Issue by mediajunkie** [cagov/covid19#4982]
- [one pager](https://docs.google.com/document/d/1OGVRkTSgRy-BGWhC4HZHsc5iRKzL2oCY9UD1y5VbwGU/edit)

![image](https://user-images.githubusercontent.com/3227378/128762297-a332f454-5ad0-466e-9406-8523e543ee81.png)

- [x] @adam-little to iterate on Jim's chart concepts
- [x] @mediajunkie  to work out chart selection process with CDPH
- [x] [prototype #5309](https://github.com/cagov/covid19/issues/5039)
- [x] [content #4921](https://github.com/cagov/covid19/issues/4921)
- [x] https://github.com/cagov/covid19/issues/5029

**Comment by mediajunkie** [comment]
Assigning to Jim for now as the remaining tasks on the list have their own tickets.

**Comment by mediajunkie** [comment]
scratch that. will make a subticket with the details...
