### ISSUE TITLE
Resume daily trackerbox updates 

### ISSUE THREAD

**Issue by mediajunkie** [cagov/covid19#5018]
- [x] Sync with @carterm to make sure the cron job & resulting JSON file will be unaffected (current assumption, @jbum )
- [x] Remove the conditional code that shows hyphens in the box on weekends (@jbum )
- [x] https://github.com/cagov/covid19/issues/5017
