### ISSUE TITLE
Lunch & Learn checklist as of Aug 5

### ISSUE THREAD

**Issue by mediajunkie** [cagov/covid19#5020]
For each event:

- [x] Update ordinal number: This one is the fourth
- [x] Line up speaker(s): Carter, Jim, Aaron, Chach
- [x] Agree on topic: communication
- [x] Check in with speaker(s) 2 weeks out
- [x] Get working title
- [x] Get blurb
- [x] Update calendar
- [x] Check in with speaker(s) 1 week out
- [x] Promote the week of
- [x] Start meeting early with background music
- [x] Record presentation
- [x] Stop recording before Q&A
- [x] Gather slide(s) from presenter(s)
- [x] Upload slide(s) to Team Drive
- [x] Upload video to Team Drive
- [x] Announce archived content in slack
- [ ] Add to some master index once it exists
