### ISSUE TITLE
Pipeline for cases by vax status

### ISSUE THREAD

**Issue by mediajunkie** [cagov/covid19#5029]
(child of https://github.com/cagov/covid19/issues/4982)

Pipeline locations:
- [x] blob file location: CDPH_COVID_GOOD_DATASETS/POSTVAX_CASE_HOSP_DEATH
- [ ] snowflake query location needed from Brendan

Pipeline workflow:
- [x] data updated weekly to the Blob at  by CDPH Science Branch (Lauren, Lawrence)
- [x] data to be uploaded from Blob to Snowflake (by Brendan/Analytica) 
   - [x] a subset of data also to be shared on ODP (may happen after launch)
- [x] An ODI cron job will get the latest data and update a JSON file (Carter will write this)
- [x] Charts will be updated with the JSON data (@jbum will handle this part)

**Comment by mediajunkie** [comment]
checking this against other sources:

<google-sheets-html-origin><style type="text/css"></style>

Cases, Hospitalizations, and Deaths by Vaccination Status (PVI) data pipeline |  
-- | --
  |  
Who | CDPH Science Branch
When | Tuesday afternoon?
What | Posts source data to the Blob (Azure)
Where | blob file location: CDPH_COVID_GOOD_DATASETS/POSTVAX_CASE_HOSP_DEATH
  |  
Who | Analytica
When | Tuesday afternoon?
What | Runs a scheduled job on Snowflake
Where | snowflake location
  |  
Who | ODI
When | Wednesday am
What | Run cron job querying Snowflake to update JSON
Where | json file location
What | Update sparklines
Where |  
What | Publish tracker update
Where | covid19.ca.gov
Where | covid19.ca.gov/state-dashboard
  |  
Who | CDPH web
When | Wednesday am
What | Publish tracker updae
Where | 2 CDPH locations
  |  
Who | ODP
When |  
What | Update open date poral
Where | get URL

**Comment by mediajunkie** [comment]
<google-sheets-html-origin><style type="text/css"></style>

Cases, Hospitalizations, and Deaths by Vaccination Status (PVI) data pipeline |  
-- | --
  |  
Who | CDPH Science Branch
When | Tuesday afternoon?
What | Posts source data to the Blob (Azure)
Where | blob file location: CDPH_COVID_GOOD_DATASETS/POSTVAX_CASE_HOSP_DEATH
  |  
Who | Analytica
When | Tuesday afternoon?
What | Runs a scheduled job on Snowflake
Where | snowflake location
  |  
Who | ODI
When | Wednesday am
What | Run cron job querying Snowflake to update JSON
Where | json file location
What | Publish chart updates
Where | covid19.ca.gov/state-dashboard
  |  
Who | CDPH web
When | Wednesday am
What | Publish ratio updates in copy?
Where |  
  |  
Who | ODP
When |  
What | Update open date poral
Where | get URL
