### ISSUE TITLE
Add clarifying content re: childcare

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#503]
### Task:
Add clarifying language

> All childcare facilities can open with necessary modifications.

To:

- [x] guidance page (child care accordion)
- [x] Stay home FAQ (if not there already) 
- [x] Add to Roadmap page under stage 2 of what is open

### Timeline: 
Thursday-by noon

**Comment by KaylaPrusia** [comment]
@abquirarte for the roadmap page, will be updating both the paragraph and roadmap graphic as they are not matching right now.

![Screenshot 2020-05-14 at 9 21 28 AM](https://user-images.githubusercontent.com/62391212/81959451-532fed80-95c4-11ea-929f-1cc0e03f171e.png)

**Comment by KaylaPrusia** [comment]
@abquirarte all edits have been made

**Comment by abquirarte** [comment]
Awesome! Let me inquire about the image, thank you for flagging @KaylaPrusia ! 💯
