### ISSUE TITLE
Pipeline updates for Trackerbox 3.0

### ISSUE THREAD

**Issue by mediajunkie** [cagov/covid19#5042]
child of https://github.com/cagov/covid19/issues/4980 

Cases, Tests, and Deaths:
- [x] no changes to pipeline needed to prototype
- [x] may request calculated fields from CPDH (Brooke, Lauren, et al.) once format is locked

Vaccinations
- [x] data already supplied for weekly updates is likely sufficient (to the Blob) from Vax taskforce (Cynthia Yee as contact)
- [x] in snowflake:
   - [ ] The daily number of vaccines administered, reported over a period of up to 90 days for the graphical sparkline: `admin_date, count(vax_event_id)` from `VW_DERIVED_BASE_DOSES_ADMIN`
   - [ ] The daily average number of vaccines administered: `admin_date, count(vax_event_id)` from `VW_DERIVED_BASE_DOSES_ADMIN`
   - [ ] The percentage of the CA population that is fully vaccinated: `fully_vaccinated` from `VW_TAB_VAX_ADMINISTERED_BY_MIXED_COUNTY` divided by `Population` from `VW_CDF_DEMOGRAPHICS_POPULATION_BY_COUNTY`

Update cron job (Carter)
- [x] Update cron job to write JSON for sparklines
- [x] Update cron job to write JSON for vax % (& possibly daily avg, sparkline range data)
- [x]  JSON file will need to now include vaccine daily average / sparkline & percent fully vaxed data

Display:
- [x] Trackerboxes to be updated with the JSON data (@jbum for ODI & ESS for CDPH)

**Comment by mediajunkie** [comment]
@carterm at some point soon-ish we will want you to change the code in the cronjob that updates the JSON that provides the data to the trackerboxes, by grabbing additional data points (for vaccination data). Should I make a related ticket for that?
