### ISSUE TITLE
Combined tracker & cases by vax status launch

### ISSUE THREAD

**Issue by mediajunkie** [cagov/covid19#5274]
_Pre-launch:_

**Everywhere trackerboxes appear**
- [x] For launch, Tests sparkline with fallback for bars
     - [x] get adam's input on options (solid, floating, and identical/redundant)
     - [x] implement solid fill (option 2)

**State dashboard**
- [x] Edits, structural changes, cross-link to vaccination progress dashboard (on V5)
    - [x] Finalize impact statement
- [x] Add Cases by Vaccination Status section (on V5)
    - [x] Include the word Cases in the H2 in lieu of tabs
- [x] Update tracker boxes (on V5)
    - [x] Update note
    - [x] Confirm if note needs to define who is included in the vaccinated population (fully and partially vaccinated)

**Home page**
- [x] Update tracker boxes
- [x] Address unique home page translation needs

**CDPH pages**
- [x] Verify updates are ready and correct
- [x] make sure production endpoint is ready
- [x] Provide production endpoint to Satya
- [x] Confirm sparklines will work in production

***QA***
- [x] Jim's sheet
- [x] state dash
- [x] home page
- [x] look at tagalog & arabic translations
- [x] test on IE 11
