### ISSUE TITLE
Tracker: clarify percent vaccinated

### ISSUE THREAD

**Issue by mediajunkie** [cagov/covid19#5632]
context: request from Dr. Pan
![image](https://user-images.githubusercontent.com/3227378/141526723-88aa84ef-b08e-4402-82c4-276cea74f451.png)

stakeholders:

- [x] float language per mock (see details below)
- [x] get approval
- [ ] confirm once live

label update;
- [x] add second stack with this language: `(5+ with at least on dose)`
- [x] make sure parallel boxes in the layout grid are consistent across the tracker
- [x] figure out if satya needs to change anything

implementation:
- [x] inform ESS / Satya of impending change
- [x] implement copy change at JSON or front-end level (@jbum) / cc @m-sullivan7
- [x] coordinate update

**Comment by jbum** [comment]
Caption added.  Created a separate ticket for the remaining cosmetic issues.

https://github.com/cagov/covid19/issues/5635
