### ISSUE TITLE
Updates to roadmap, guidance, and county pages, per GO 

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#630]
Received request Sunday evening to make changes to a few pages:

1. FAQ @KaylaPrusia 
2. Roadmap @LizNobriga 
3. County @ashleydraper 

I've made the changes to Monday's requests. -AQ

Changes to Monday and Tuesday planning for website:

- On Monday, we will move statewide on in-store retail, shopping malls, and places of worship. 
- On Monday, we will post updated Q&A on "protected activities" (attached)
- On Tuesday, we will move on hair salons for counties with variance only

We will need to make the following modifications to COVID-19.ca.gov, to which the Public Health order points as the control language for re-opening:

MONDAY

- [x] - Add guidance documents for places of worship (attached) to the statewide guidance page 
- saved in Gdrive, loaded to Github
- [x] - Move shopping malls guidance from the variance page to the statewide guidance page
- [x] - Amend the language across the website that limits retail to curbside only.
- [x] - Add Q&A language on protected activities
- [x] Update sub-nav to reflect change from Political activity, to **protected** activities

TUESDAY

- [x] - Add guidance on hair salons to the county variance page. (Already in Github)
- [x] - Amend language across the website to reference hair salons in counties with variance.

**Comment by KaylaPrusia** [comment]
@abquirarte Drafted updates on [Stay Home QA](https://docs.google.com/document/d/14IL8TJMfBCZXcZ8lMph7aastRl3o7ym3/edit#) re: what's open/closed and added updated DMV info (bottom of page). reviewed by @thepegisin

**Comment by abquirarte** [comment]
Looking thank you!
